# Generated by Django 5.0.6 on 2024-06-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0008_question_category_alter_answer_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question", name="views", field=models.IntegerField(default=0),
        ),
    ]
